# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build-to-github-packages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: yarn
      - name: Configure Github Packages authentication
        run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmRegistryServer https://npm.pkg.github.com
          yarn config set npmPublishRegistry https://npm.pkg.github.com
          yarn config set npmAuthToken ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Github packages
        run: yarn npm publish
