# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:

jobs:
  build-to-github-packages:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: yarn
      - name: Configure Github Packages authentication
        run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmRegistryServer https://npm.pkg.github.com
          yarn config set npmPublishRegistry https://npm.pkg.github.com
          yarn config set npmAuthToken ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm test
      - name: Setup npm auth
        run: |
          echo "@Aetherinox:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PAT }}" >> ~/.npmrc
          npm login
          npm adduser
      - run: npm publish --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
